### ISSUE TITLE
Assuming I just compiled a debug build...?? 

### ISSUE THREAD

**Issue by microfx** [librespot-org/librespot#1126]
Hey!

In the COMPILING.md is written:
***
Assuming you just compiled a ```debug``` build, you can run librespot with the following command:

```bash
./target/debug/librespot
```
***
...so apparently I have built a debug build. And I don't know why. Can anyone tell me? :D I don't want to have a 278 MB binary. The instructions are really not understandable ... I'm not a dev and don't want / need a debug build probably. 

```
cargo build -j 3 --no-default-features --features rodiojack-backend --locked
```

this is how I build. Any ideas how to not have a debug build?

**Comment by kingosticks** [comment]
`cargo build --help` has lots of help. There's also documentation at https://doc.rust-lang.org/cargo/commands/cargo-build.html

Add the `--release` flag to your command to build an optimised version. It'll perfom better than a debug build, which is usually far more important than the size of the binary but [there are ways to make it smaller]( https://www.google.com/search?client=firefox-b-m&sxsrf=AJOqlzW3YWmGApmx5aH6CdWmloRpRxyBGg%3A1677955738214&q=how+to+strip+a+rust+binary&oq=how+to+strip+a+rust+binary).

Next time, maybe post a new discussion topic rather than an issue. Issues are generally for bugs and feature requests. I don't think we need to reproduce general Rust documentation here.

**Comment by microfx** [comment]
Okay, thanks for the super quick help! Will do – not too familiar with all of this wizardry!
