### ISSUE TITLE
Spotify for Artist doesn’t count streaming with new LIBRESPOT

### ISSUE THREAD

**Issue by enricobuja** [librespot-org/librespot#1174]
Hi, there is an important problem in the new librespot! Volumio software installed on raspberry pi zero w using this new library for his Spotify connect plug-in and the problem is that Spotify for artist doesn’t count the streaming made from this plug in that use your library for connect to Spotify library. The old plug in was perfect because used the old version of librespot and the streaming count was every time regular, but now ZERO! this is important because is like a pirate protocol streaming now, because Spotify doesn’t pay the royalty to the artists in this case because this library doesn’t permit the count of it! So please check what is change from old to new library and correct otherwise is against the law! Let me know updates so I can try if the problem is correct thanks.

**Comment by michaelherger** [comment]
See also https://github.com/librespot-org/librespot/discussions/626

**Comment by kingosticks** [comment]
> and correct otherwise is against the law! 

... OK.

As per the linked issue above, reporting has not worked since at least 2019 - I'm pretty sure reporting has never worked. But you appear to be saying it used to work and now doesn't. So can you please clarify how #626 differs from what you are describing and also provide the revision where it used to work.

**Comment by roderickvd** [comment]
Indeed seems like a duplicate to me.
