### ISSUE TITLE
Handle reconnection for Sessions

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#134]
This issue serves as a placeholder for discussion around the rewrite of the session handling logic, as it is currently one of the less stable parts of librespot. Issue #103 is related to this.

**Comment by sashahilton00** [comment]
@plietar did you find that initial implementation anywhere?

**Comment by sashahilton00** [comment]
Regardless, I think we should be aiming to make this as simple to integrate as possible, as handling reconnection logic from whatever project uses librespot sounds like plenty of headache for anyone who tries to use librespot, whilst also being pretty low level functionality that I personally would expect to be handled in any library I used. Anyway, these are just my two cents since I'm not sufficently versed in rust to be able to rewrite how sessions are handled. Would be good to hear others thoughts as to how this should be handled.

**Comment by lrbalt** [comment]
I am trying to wrap my head around this issue. 

AFAICS, the disconnect error starts at `Session::DispatchTask::poll. The error causes the `invalid` flag to be set on `Session` (patch #206) and the error is returned from the future and picked up by the `map_err` on `Session::connect` which only logs an error. Both `Spirc::poll` and `Player::poll` check on a valid session and they shut down if they notice that the session is invalid, freeing all resources like `mercury`

Since `Player` is managed by `Spirc`, I think we can improve this by only checking on `Session` at  `Spirc::poll` and let `spirc` inform `Player` to stop/shutdown.

`main` currently does not notice the lost connection at all which is probably wrong since it does not clean up `spirc` and `spirc_task` and `player_event_channel`. But they are replaced when a new connection is made, so no real harm done. This can be improved by letting `spirc_task` return an error and handle this in `main`.

So this works for the binary case.

For the library case @plietar suggests to let main reconnect using last credentials and let Spirc, Player, etc. pick up the new session and reset its state accordingly. I have two problems trying to implement this
* session is currently  a future which requires AFAIK a `'static` lifetime. Making Session::new causes the Session state to be non-static. I couldn't get `Session::new()` followed by `Session::connect(&mut self)` to work because &self not being `'static`
* why is it difficult for the library to let main recreate `Session/Spirc/Player` from the credentials that main manages anyway? We could let `Spirc` return with a `ConnectionError`? I'm trying to figure out the use case.

If you look at examples/play.rs you can do a match on `core.run(player.load(track, true, 0))` and handle the `ConnectionError`??

**Comment by maciex** [comment]
Is there any way to mitigate this problem?
Is it possible to somehow detect that it disconnected and restart it manually (using some shell script)?

**Comment by oboote** [comment]
> Is there any way to mitigate this problem?
> Is it possible to somehow detect that it disconnected and restart it manually (using some shell script)?

This doesn't address the cause but aids with the symptoms:
https://gist.github.com/JeremieRapin/bc35a2632c072a082d48f5503270df16

Script to be run as a cronjob every minute which checks the status and restarts the service if an error is spotted.

**Comment by cdlenfert** [comment]
Is the cronjob patch the best solution for this issue currently? Sometimes I'm 25 songs in, sometimes I'm 4 when I lose connection. This is running on a server connected directly to my modem/router via ethernet. I can't imagine it's actually losing internet connection this consistently.

**Comment by willstott101** [comment]
> This can mean various things depending on the component. `Spirc` for example should reset its state if the username is different, and reestablish the mercury channel.

Sounds like this is closely related to, and would probably help solve #266
