### ISSUE TITLE
librespot mdns reponder competes with avahi -> forces avahi to add '-2' to the hostname

### ISSUE THREAD

**Issue by ernstkl** [librespot-org/librespot#1379]
### Look for similar bugs
done

### Description

When librespot is running, and
- later avahi is started / restarted
or
- network-connectivity is lost and restored again

avahi will find a hostname conflict when trying to claim the system host name \<hostname\>, and has to resort to register \<hostname\>-2

The result is that the original \<hostname\>.local can not be resolved by other hosts in the LAN.

### Version
any, incl. 0.5.0

### How to reproduce
Steps to reproduce the behavior 
1. start librespot in any way
2. systemctl restart avahi-daemon
3. look at the logs, find the entry "\<hostname\> avahi-daemon[404]: Host name conflict, retrying with \<hostname\>-2

### Log
* I am not adding a librespot debug log, because librespot works fine, it just stands in the way of avahi working correctly

### Host (what you are running `librespot` on):
- OS: Linux
- Platform: RPi 4

### Suggested fix (concept)

Starting the mdns responder should be done using [spawn_ip_with_ip_list_and_hostname](https://docs.rs/libmdns/latest/libmdns/struct.Responder.html#method.spawn_with_ip_list_and_hostname), and choose a hostname _derived_ from the system hostname, like "librespot-on-\<hostname>\", or maybe same random value.

suggestion based on  (https://github.com/avahi/avahi/issues/117#issuecomment-2424893440)

(edit: escape the \> and \< around hostname)

**Comment by wisp3rwind** [comment]
I think this is an issue with the `libmdns`-based zeroconf stack only: As I understand it, its mainly supposed to be used if you don't want to run another MDNS service on the system just for librespot. There's some discussion on the original motivation for adding it at https://github.com/plietar/librespot/issues/33.

If you have Avahi running already, you should be able to compile librespot with the `with-dns-sd` feature, which talks to Avahi (via the `dns-sd` compatibility layer, which you'd need to install, cf. https://github.com/librespot-org/librespot/wiki/Compiling#with-dns-sd).

#1347 proposes to add yet another Avahi-based zeroconf interface to librespot and makes switching between the different configurations more convenient (by adding a commandline flag, instead of just a compile-time feature, and by not requiring non-Rust dependencies).

Your suggested fix sounds like a worthwhile improvement we could do; and we could probably also do a better job of documenting this behavior.

**Comment by wisp3rwind** [comment]
One thing we could do on top of #1347 is to add an `auto` zeroconf backend, which tries to connect to Avahi, and falls back to `libmdns` if that's not running. We might then make this the new default (i.e. add `with-avahi` to the default features and select the `auto` backend by default when using the CLI).

**Comment by wisp3rwind** [comment]
Relevant history: https://github.com/plietar/librespot/issues/33, https://github.com/plietar/librespot/pull/81.

**Comment by redraw** [comment]
Still happening by default,

```
Mar 30 12:47:21 moode avahi-daemon[168055]: *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
```

I had to change the avahi daemon hostname, otherwise avahi fallbacks to <hostname>-2.local. 

Also, librespot somehow publishes the first IP it finds from any interface, sometimes the LAN ip, sometimes the docker bridge IP, sometimes the tailscale IP.

```
+  wlan0 IPv4 Moode                                         _spotify-connect._tcp local
=  wlan0 IPv4 Moode                                         _spotify-connect._tcp local
   hostname = [moode.local]
   address = [100.120.152.64]
   port = [45095]
   txt = ["CPath=/" "VERSION=1.0"]
```

There are workarounds for sure, but defaults are not sensible for all users.
