### ISSUE TITLE
Volume normalization

### ISSUE THREAD

**Issue by cortegedusage** [librespot-org/librespot#15]
I think volume normalisation also should be added to this repo.
I've been using
https://github.com/herrernst/librespot/tree/volume-normalization/src

for a couple of weeks now, and it's working quite well

**Comment by alin23** [comment]
@cortegedusage Sounds good! 
I will prepare a PR for this if @ComlOnline is ok with it.

**Comment by ComlOnline** [comment]
Yeah that would be great, the only thing I ask is that you add a compile time flag like --features "normalization" as we're discussing in other [issues ](https://github.com/librespot-org/librespot/issues/7#issuecomment-361105399)we plan on keeping librespot relatively slimline in its default build state and also have a proper daemon style thing with all the bells and whistles.

**Comment by herrernst** [comment]
@ComlOnline I don't see a point hiding this few lines of code (that don't have any dependencies) behind a compile-time feature flag; also, they are not executed if the command line flag isn't added when running.

@alin23 If you don't mind waiting, I will prepare a pull request in the next days which fixes the edge cases where clipping (distortion) does occur.

**Comment by alin23** [comment]
@herrernst I can wait ^_^

**Comment by ComlOnline** [comment]
@herrernst I see your point and you are correct. I didn't see the command line flag, my fault.  
My next question is should normalization be the default function and you have to pass a flag to turn it off?  
I think most people would unknowingly appreciate this.

**Comment by herrernst** [comment]
I now consider my branch ready for merging: https://github.com/herrernst/librespot/tree/volume-normalization
I wouldn't want this feature enabled by default; the remaining problem is that I'm not able to figure out if an album is played vs. a playlist, so it only applies track-specific normalization. But that is not what you want if you play an album, because you lose inter-track dynamics, and if there are gapless transitions (like a live album), volume would change abruptly when changing tracks.

**Comment by ComlOnline** [comment]
@herrernst Please could you make a PR?

**Comment by sashahilton00** [comment]
Added by #162
