### ISSUE TITLE
Shuffle/Repeat buttons are not fully functional.

### ISSUE THREAD

**Issue by mrwsl** [librespot-org/librespot#19]
Good to see you guys keep this project alive!

Basically copy/paste from [plietar's repo issue #82](https://github.com/plietar/librespot/issues/82)

**Comment by ComlOnline** [comment]
Just so you know the shuffle and repeat from @kingosticks was added in #2, I know there are still some things to fix so I'll keep this open:

See his comments [here](https://github.com/plietar/librespot/issues/82#issuecomment-349741285) and [here](https://github.com/librespot-org/librespot/pull/2#commitcomment-25654241).

**Comment by kingosticks** [comment]
> Unfortunately it's only half done, if you disable shuffle it doesn't go back to the original track order like the official client does. I can't work out an elegant way to solve this, my only idea is to make another copy of the tracklist and restore that when shuffle is disabled

An update in regards to the above. It's become obvious this isn't a good idea as librespot may have never seen a non-shuffled version of the tracklist (e.g. a mobile client shuffled the tracklist whilst disconnected from the network). Re-fetching the tracks from the context uri is simplest. You just have to ensure you save the queued tracks before doing so as they are not part of the context and would otherwise be lost. I think the official Android client has a bug here as if you enable/disable shuffle a few times in a row you sometimes suddenly lose the queued tracks.

**Comment by kingosticks** [comment]
The different repeat modes (single vs all) is still covered by this issue but the remaining shuffle part of this is superseded by https://github.com/librespot-org/librespot/issues/264

**Comment by louy2** [comment]
Running into this, cannot repeat a single track. Anything I can help with?

**Comment by roderickvd** [comment]
Will be tackling this under `new-api` efforts.

**Comment by wael444** [comment]
Status?

**Comment by roderickvd** [comment]
Same.

**Comment by deathslittlegirl** [comment]
Status?

**Comment by roderickvd** [comment]
Come on.

**Comment by noirelapine** [comment]
would like to see this happen as well.

**Comment by deathslittlegirl** [comment]
In hindsight I should likely apologize as I came into this discussion section with frustration and confusion. I have no intention of rushing your development or forcing you to tunnel vision on just the repeat function. It's actually not that big of a deal in my life, Spotify. Continue focusing on what's important and spotifyd will be everything you're seeing ahead. Best of luck to you.

**Comment by roderickvd** [comment]
Reporting back after some time: with the current `spirc` we have no way of indicating that we support single repeat mode, so the client doesn't offer it. Maybe it will be possible when we start publishing our device capabilities on HTTPS, which is targeted for v0.5. Otherwise it will require the `dealer` interface which will certainly have to wait until v0.6.

**Comment by arch-btw** [comment]
> Running into this, cannot repeat a single track. Anything I can help with?


For anyone facing this issue, the repeat single track option works with **librespot-java**, this might be a temporary solution until this gets fixed in the Rust version 👍

**Comment by wael444** [comment]
i would rather live with the proprietary spotify client than to have to use that

**Comment by KevinLee3627** [comment]
Is there any update on shuffle functionality?

**Comment by roderickvd** [comment]
`librespot-java` has implemented it. Basically it's a complete move away from Mercury-based `spirc` towards a web socket interface. One could port it from `librespot-java`: it requires major breaking (i.e. non-incremental) changes under the hood of `librespot`.
