### ISSUE TITLE
Get rid of Rust fmt

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#208]
Rust fmt does not seem to be as stable as we thought it was. I think it would be better if we just disable it on travis and wait for things to stabilse. The recommendation would still be to run rust fmt on commits, but it would mitigate these cases where PR's have to be updated due to formatting.

**Comment by plietar** [comment]
I agree, this was a mistake. Sorry.

We could instead of requiring the entire codebase to be always properly formatted only require it for files which have been modified.

This can still cause issues, but less frequently than in today's situation. Ultimately we would want to only check the lines that have been touched by the PR, but rustfmt doesn't support this yet.

**Comment by sashahilton00** [comment]
Removed from travis in https://github.com/librespot-org/librespot/commit/d76d9725e083648a628d6205296deb6ec6b984e6
