### ISSUE TITLE
Compile for arm6l

### ISSUE THREAD

**Issue by moodeaudio** [librespot-org/librespot#258]
Hi, 

I'm seeing "Illegal instruction" when running librespot on a 0W.

My compile procedure is below and its run it on a 3B+

sudo apt-get -y install portaudio19-dev
cd ~
git clone https://github.com/librespot-org/librespot
curl https://sh.rustup.rs -sSf | sh
NOTE: choose 1
sudo reboot
cd librespot/
cargo build --release --features alsa-backend
sudo cp target/release/librespot /usr/local/bin

Is there a cargo param for arm6l, or possibly does it need to be compiled directly on arm6l ??

-Tim

**Comment by ashthespy** [comment]
I reckon you mean the Raspberry pi ZeroW? 
With the steps you outlined above, you built it for the host processor of your device (3B+).
For the pi0, since it supports hard float, you can use the [docker image to cross compile](https://github.com/librespot-org/librespot/wiki/Cross-compiling) for it with:

```shell
docker build -t librespot-cross -f contrib/Dockerfile .
docker run -v /tmp/librespot-build:/build librespot-cross contrib/docker-build-pi-armv6hf.sh
```

**Comment by moodeaudio** [comment]
Thanks and yes, the armv6l Pi's (1B, Zero and Zero W).

I assume that end result is separate binaries, one for armv7l and another for armv6l, correct?

**Comment by kingosticks** [comment]
The armv6 binary will work on all flavours of raspberry pi. In the same way that the foundation's raspbian does.

**Comment by moodeaudio** [comment]
I did not know that :-0

Just performed a quick test using a librespot binary that was compiled on a Pi-ZeroW (armv6l) and indeed it runs perfectly on a Pi-3B+ :-) I suppose I should investigate the cross-compile since the little Zero W took all day to make librespot!

How are the build params specified in the docker cmd below? Just tack them on the end?
 --release --features alsa-backend

docker run -v /tmp/librespot-build:/build librespot-cross contrib/docker-build-pi-armv6hf.sh

**Comment by ashthespy** [comment]
@moodeaudio The docker image uses the [foundations tool chain](https://github.com/raspberrypi/tools/) to build armv6 with floating point support.

For your second question - I see that I have [hard-coded the back-end](https://github.com/librespot-org/librespot/blob/d12640fb478cc6536ae798057bbc6d1c84e0c598/contrib/docker-build-pi-armv6hf.sh#L42), but it should be easy to pass in the parameters to the script.

**Comment by moodeaudio** [comment]
Cool.

Is there a particular version of docker thats required?

I'm seeing version 1.5 in the the Stretch repo.

pi@rp3:/usr/local/bin $ sudo apt-get -s install docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst docker (1.5-1 Raspbian:stable [armhf])
Conf docker (1.5-1 Raspbian:stable [armhf])

**Comment by ashthespy** [comment]
Hmm - I see your running this all from the pi3 - then I think `curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh` gets your docker on the pi3. 
But if you ask me, I would directly cross compile from the pi3 rather than go through the docker route on that device.

**Comment by moodeaudio** [comment]
Thats what I would like to do, x-compile using the 3B+ and generate the armv6l binary which will work equally well on arm6 or 7.

But I don't have any experience with docker, cargo, rust etc., and so I'm having a bit of a time understanding the recipe.

So far, if I understand correctly

curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
docker build -t librespot-cross -f contrib/Dockerfile .
docker run -v /tmp/librespot-build:/build librespot-cross contrib/docker-build-pi-armv6hf.sh

And since the script "docker-build-pi-armv6hf.sh" has alsa-backend hard coded I should be god-to-go ?

**Comment by moodeaudio** [comment]
Thanks, I'll give it a try in the coming days :-)

**Comment by b26x** [comment]
Hey there, 
after countless hours of trying to cross compile on my Intel machine, I'm unfortunately not sure what else to give a try.

while running `docker build -t librespot-cross -f contrib/Dockerfile .` an error occurs

this is what seems to be the important part of the output:

> #9 35.08 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#9 35.08 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#9 35.08 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#9 35.08 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-arm64/Packages  404  Not Found [IP: 151.101.130.132 80]
#9 35.08 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-armhf/Packages  404  Not Found
#9 35.08 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found
#9 35.08 E: Some index files failed to download. They have been ignored, or old ones used instead.
executor failed running [/bin/sh -c apt-get update]: exit code: 100

Maby the problem is obvious - i'm still very new to this kind of stuff.
Any help would be highly appreciated.
