### ISSUE TITLE
Librespot connection issue

### ISSUE THREAD

**Issue by t0k4rt** [librespot-org/librespot#278]
Hello all, 
I'm seeking guidance about a network issue.
I got a router hardware upgrade from my isp. 
Since then I cannot connect.
My internal newtork has ipV6, I disabled it but it changed nothing

My questions:
Is there any debug mode for librespot ?
What tool could I use to debug this ?
Can it be a NAT traversal problem ?
Does spotify connect uses upnp ?

thanks for your insights

**Comment by johncalvinyoung** [comment]
It’s quite possibly a broken multicast implementation in your ISP router. I had a similar problem, and discovered that the otherwise-excellent router essentially could not forward multicast correctly (I think it WOULD work for IPv6 and not IPv4, but Spotify prefers the other, or something like that), and multicast -> zeroconf/avahi/Bonjour -> mDNS -> how librespot advertises itself on the network as an available speaker.

**Comment by t0k4rt** [comment]
Thanks for your response, 
Sorry but I forgot to mention that it appears correctly in my spotify connect devices.
The problem is that it refuses to connect on my internal network.
On my work network it works properly. 
I can't see what could block
thanks again for your help !

**Comment by ashthespy** [comment]
Logs are available by running `librespot`  with the `--verbose` flag. 
`librespot` uses the [`env_logger`](https://docs.rs/env_logger/0.5.11/env_logger/#example) module to handle logs internally.  
So `RUST_LOG=mdns=trace ./librespot` with your usual arguments will enable logs for the `mdns` module.  Might help you figure out whats going on.

**Comment by t0k4rt** [comment]
Thanks a lot, 
I'll try this asap !

**Comment by t0k4rt** [comment]
Ok, I found the solution
It was related to my new isp router which was filtering all outbound connections by default.
Thanks for the help and sorry for the disturbance !
