### ISSUE TITLE
Implement 'autoplay' functionality

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot#294]
Sometimes if I let Spotify run for a long time period I come to the end of my playlist, especially if it's really short. Therefore I have in my Spotify Desktop Client the option enabled to play similar songs on the end of the playlist.
![screenshot-20190302150052-931x113](https://user-images.githubusercontent.com/27705384/53683007-1435b500-3cfc-11e9-99ff-1162a3fcb01a.png)

I noticed this was not working when using librespot, would it be possible to implement this?

Regards.

**Comment by devgianlu** [comment]
This doesn't seem to be communicated to the player, so it'll have to be an option inside `librespot`. I suppose you need to turn off repeat in order for this to work. Right?

**Comment by xMordax** [comment]
Exactly, repeat has to be disabled this to work.

**Comment by devgianlu** [comment]
Stole the idea and implemented it in `librespot-java`!

**Comment by sashahilton00** [comment]
@devgianlu was there any reverse engineering required, or are you just pulling the queue again once the local queue ends?

**Comment by devgianlu** [comment]
I am using the `hm://radio-apollo/v3/stations/` endpoint to create a station for the given context and they I play it like a standard station.

**Comment by ashthespy** [comment]
FWIW: There is an endpoint for this, didn't look into it in detail though.
`hm://autoplay-enabled/query`

**Comment by devgianlu** [comment]
@ashthespy Is there anything more to it? Doing `GET hm://autoplay-enabled/query` returns `400`.

**Comment by ashthespy** [comment]
@devgianlu Sorry, no I didn't have time to dump more packets and investigate. But it seems to follow the format of `hm://autoplay-enabled/query?uri=spotify%3Auser%3A` where the uri is of the current playlist.

**Comment by sashahilton00** [comment]
@devgianlu @ashthespy it's pretty simple. You just send a request to the autoplay endpoint as follows:

`hm://autoplay-enabled/query?uri=spotify:user:sashahilton00:playlist:5fFTfhV...jqkezuVT`

You'll then get a response, which is just a URI to a station for that playlist:

`spotify:station:user:sashahilton00:playlist:5fFTfhV...jqkezuVT`

Use the normal endpoint to get the JSON payload for the station:

`hm://radio-apollo/v3/stations/spotify:station:user:sashahilton00:playlist:5fFTfhV...jqkezuVT`

Then you'll get a JSON payload, which can then just be played like a station normally is. Makes sense that it's a toggle in the client, since the only thing it does is wait for the queue to empty, then makes the above requests and starts playing the radio for the given playlist.

**Comment by devgianlu** [comment]
My implementation is obsolete then. What if autoplay is disabled? Does it still make the request?

**Comment by sashahilton00** [comment]
Haven't checked, but given it's a client toggle, I imagine if it's disabled it doesn't, and just stops playing once playlist/album is finished

**Comment by devgianlu** [comment]
Anyone tested this? I keep getting `204`.

**Comment by ashthespy** [comment]
I have the same as @sashahilton00 - the endpoint responds with the station `uri` in plain old bytes.

**Comment by otrsk** [comment]
Any status updates on this one? (Such a feature would be amazing indeed!) 

One possible workaround is of course to use something like shairport ( https://github.com/mikebrady/shairport-sync ) as, this way, the stream is managed by the user device (phone) and autoplay just works.
