### ISSUE TITLE
Error sending packet os

### ISSUE THREAD

**Issue by Csierra099** [librespot-org/librespot#326]
Hey guys so Im using raspotify in a hotel to manage all the music but since we bought the pi and installed raspotify we have encountered an issue that has to do with error sending packet os, the actual problem is that spotify stops playing songs after playing a few of them, I asked directly to the raspotify and they told me that the issued has to with librespot, does any one know why this happens? 

Apr 01 13:46:36 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }

Apr 01 13:46:38 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }

Apr 01 13:46:45 MediaCenter librespot[435]: WARN:<unknown>: error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }

**Comment by sashahilton00** [comment]
This is  case of the client trying to listen on an address/port combo that is not available on the device. this is not a librespot issue, but rather a device config issue. If you still have this problem and need assistance with troubleshooting, you can ask on the librespot gitter, and hopefully someone will assist. Since this is not an issue with the library, closing.

**Comment by dangerfish96** [comment]
Sorry for writting on a closed issue, but is it possible to know which address/port is meant in the error?
