### ISSUE TITLE
Pipe plays to fast

### ISSUE THREAD

**Issue by dflvunoooooo** [librespot-org/librespot#340]
If I redirect the librespot output via pipe to a fifo file the music is a little bit to fast, just enough to notice and to nag. This happens as well with the `… --backend pipe >` or with `--backend pipe --device /tmp/snapfifo-Spotify`.

If I start librespot without the pipe option it plays in normal speed.

There is no error message nor anything wich would show a problem. I use librespot 12.1.51-7 on a Arch Linux desktop.

Has anyone an idea how to solve this issue? I would like to run librespot on a headless server, wich will not have pulseaudio.

Edit: typo.

**Comment by kingosticks** [comment]
When using the `pipe` backend, raw PCM is written to the file as quickly as it's downloaded and it's entirely the job of the other side to handle playback i.e. snapcast's job.

**Comment by dflvunoooooo** [comment]
A I see. Thank you very much for pointing that out.

**Comment by dflvunoooooo** [comment]
In case someone stumbles over this, the solution is to set the sample rate of snapcast to 44000Hz. I got help on from here [https://github.com/badaix/snapcast/issues/464#issue-460636537](url).

In my case it is now something like this
`SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo?name=snapcast&sampleformat=44000:16:2`.

**Comment by willstott101** [comment]
Glad you sorted it! I'm pretty sure that ought to be 44100 though technically.

**Comment by dflvunoooooo** [comment]
Can you explain to me why?

**Comment by ashthespy** [comment]
I have been playing around with variable sample rates with lewton and ALSA after https://github.com/RustAudio/lewton/commit/dad57f2c71ff50965feaf26ce8a478320684b8b6, but haven't gotten to testing it extensively. Should probably get some DACs that do variable rates and play around more...

**Comment by dflvunoooooo** [comment]
A interesting, didn't know that. Maybe I should get a metronome to check what works best.

**Comment by willstott101** [comment]
The decoded data from Spotify is always 16 bit 44.1kHz as far as I know. Does ogg support variable sample rates? I've never heard of that in audio before

**Comment by dflvunoooooo** [comment]
Thank you. 
Ogg does support variable bitrates, as far as I know. Of what haven't you heard?

**Comment by kingosticks** [comment]
That 44kHz fix is odd, I am surprised to hear that's required. That linked issue doesn't work for me. 

Sample rate is not the same as bit rate. A variable sample rate would be odd. I've never heard of that being used either but I'd be interested to hear the reasoning behind it.

**Comment by kingosticks** [comment]
Just to be clear for anyone else landing here, the correct sample rate to use is 44**1**00, not 44**0**00. So the snapcast setting would look like:
```SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo?name=snapcast&sampleformat=44100:16:2".```

From https://github.com/badaix/snapcast/issues/464#issuecomment-507621402

**Comment by itskevinb** [comment]
Hitting this in 2026-05 with a snapcast multi-room setup, writing up the fix in case it helps someone else.

**Symptom:** With `librespot --backend pipe` writing to `/run/snapfifo` consumed by snapserver, tracks would *load* in rapid bursts (multiple per second in librespot logs) but no audio ever flowed — snapserver `stream` status stayed `idle`. Spotify mobile/web/desktop would auto-skip through the entire queue within seconds, then mark the device inactive. `WARN librespot_connect::state::context] couldn't load context info because: context is not available. type: Default` was consistently present.

Same librespot binary, same Spotify account: `--backend alsa` endpoints (Music Room with a real ALSA device) worked perfectly. Only the pipe-backend endpoint failed.

**Things that did NOT help in our case** (worth listing so others can skip them):
- librespot dev branch HEAD vs 0.8.0 release
- `--autoplay off`, `--disable-gapless`
- Renaming the device, clearing cached credentials, Spotify "Sign Out Everywhere"
- Direct `librespot ... > /run/snapfifo` (no ffmpeg)
- Adding `ffmpeg -re` as a real-time pacer (this is sometimes recommended, but in our case librespot was idle in `do_epoll_wait` and ffmpeg had `wchar=0` — pacing isn't the issue when librespot isn't writing in the first place)
- Switching the host from an unprivileged LXC to a full VM (ruled out container kernel quirks)
- 44.1k end-to-end (no resample), snapclients resampling locally

**What fixed it:** switching from `--backend pipe` to `--backend alsa` via `snd-aloop`, mirroring our working ALSA endpoints.

`/etc/modules-load.d/snd-aloop.conf`:
```
snd-aloop
```
`/etc/modprobe.d/snd-aloop.conf`:
```
options snd-aloop pcm_substreams=1
```

Rebuild librespot with the alsa feature (cargo's default install lacks it):
```
cargo install librespot --version 0.8.0 --force --locked --features alsa-backend
```

librespot launcher (`librespot-innout.service`):
```bash
exec librespot --name "MyEndpoint" --backend alsa --device hw:Loopback,0,0 \
  --format S32 --bitrate 320 --device-type speaker \
  --cache /var/cache/librespot --zeroconf-port 5051
```

Separate bridge service that reads the loopback capture side and writes PCM to snapfifo (`snapfifo-bridge.service`):
```bash
exec ffmpeg -nostdin -loglevel error \
  -f alsa -acodec pcm_s32le -ar 44100 -ac 2 -i hw:Loopback,1,0 \
  -af aresample=resampler=soxr:precision=28:dither_method=none \
  -ar 96000 -ac 2 -c:a pcm_s32le -f s32le pipe:1 \
  > /run/snapfifo
```

snapserver source: `pipe:///run/snapfifo?name=MyEndpoint&sampleformat=96000:32:2&codec=pcm`.

The snd-aloop kernel module gives librespot a real-time-clocked audio sink (which the pipe backend doesn't), and Spotify's Connect controller then treats the device normally. Snapserver stream goes to `playing` within a second of pressing play and stays there.
