### ISSUE TITLE
Improve development process

### ISSUE THREAD

**Issue by HEnquist** [librespot-org/librespot#385]
This development process for this project is not ideal. There is no versioning, and all PRs merge directly to master, which is also the only active branch. This might be ok for a small project with few contributors, but librespot is far too big.

I would suggest starting simple:
- Creating a "develop" branch.
- All PRs go to "develop". 
- Now and then, when the develop branch is in a good state, it's merged to master-
- When develop is merged to master, a tag is created with a version number following semantic versioning.

Other ideas and suggestions?

**Comment by kingosticks** [comment]
* Add CI builds to PRs. No merge unless passing. Maybe with some more example to get better coverage.

I tried to find some kind of protobuf replay/mocking library for integration testing (like pyvcr) but couldn't find anything.

**Comment by ashthespy** [comment]
Also relevant - https://github.com/librespot-org/librespot/issues/130

**Comment by HEnquist** [comment]
Many good points in that discussion! And most people seemed to more or less agree, but then nothing happened.
Being able to specify a tag would be a big help for any project depending on librespot yes. And for those who don't specify, having a separate development branch would help making sure that master is always good.

Travis already builds PRs, but yes it would be very good to extend the examples and add them to CI.

**Comment by SirWindfield** [comment]
Are you guys ok with moving to GitHub Actions? I have workflows that can just be dropped in without modifications whatsoever that trigger on PRs. I can extend them to create a tag when pushing to master without a lot of work.

**Comment by sashahilton00** [comment]
It should also be the case that, ideally, when a release is tagged and pushed to master, the varoius crates are built and pushed to crates.io. Saves us having to remember to manually publish the packages.

**Comment by HEnquist** [comment]
Github Actions seems like a good idea. I haven't had time to try yet but it seems like an competitor to Gitlab CI/CD which is very useful.
Anyway I think we need the maintainer to join this discussion. @awiouy ?

**Comment by SirWindfield** [comment]
I can open up an issue that adds the workflows this weekend :)

**Comment by ashthespy** [comment]
Github actions aren't enabled yet for this repo/organisation, will probably need to [signup](https://github.com/features/actions/signup) via the organisation account.

**Comment by kingosticks** [comment]
Could we start with adding a 2nd branch? It shouldn't take 5 mins. And then also deciding which one you want to be the default on here, I suggest the develop branch else everyone unknowingly opens their PRs against the stable branch. It is of course trivial to change that afterwards.

**Comment by sashahilton00** [comment]
I can do that now if you want. Have enabled actions @ashthespy. Not sure if @awiouy has a ton of time atm?

**Comment by ashthespy** [comment]
Also created `dev` -- lets figure out what works best!

**Comment by sashahilton00** [comment]
I suggest we just set that to master and get on with it. It'll require people to update their git configs, but tbh it has to be done at some point so might as well be now?

**Comment by sashahilton00** [comment]
Have changed it to dev. I also think we should get any PRs that are good and waiting to merge merged, then create a release, and get `0.1.0` pushed to crates.io. it may not be perfect atm, but at least its a starting point.

**Comment by SirWindfield** [comment]
I think I've got an email today saying github actions is available for everyone

**Comment by ashthespy** [comment]
@SirWindfield It's already been enabled on this repo..

**Comment by ashthespy** [comment]
The wiki is quite out of date, especially the section on Compiling/Development. The various feature flags are also not fully documented.  Any volunteers? 

Also what is the consensus on `rustfmt`? I would propose to bite the bullet and update the entire codebase to Edition 2018 and format once.

**Comment by sashahilton00** [comment]
I'm indifferent to rustfmt to be honest. It's been a pain in the past, it confuses would be contributors when Travis breaks, and it is just a superficial change. Whilst I'm in favour of having rustfmt as the style guide for the project, I'd rather just have someone run it every now and then as opposed to seeing potential PRs and contributions delayed. Similarly, if someone working on the project feels that the style throughout absolutely must be consistent, they can always run it and update as part of their PR. I'd stick a note in contributing along the lines of `It is recommended that you run rustfmt on your code before submitting a PR.`

Just my 2 cents. If anyone else feels differently/strongly feel free to overrule.

**Comment by SirWindfield** [comment]
Best would be a simple pre-commit hook that runs rustfmt :)

**Comment by michaelherger** [comment]
> Best would be a simple pre-commit hook that runs rustfmt :)

IMHO this is a major pain for anyone who's trying to keep a fork up to date. Sometimes I've spent more time solving merge conflicts due to formatting than with the actual code changes.

**Comment by sashahilton00** [comment]
Hmm, you're right on that, didn't think of it but thinking back to when we had rustfmt I also had my fair share of merge conflicts due to formatting...

**Comment by ashthespy** [comment]
I feel you pain as well on the forks front, but IMO we had `rustfmt` running way before it hit stable, and thus making a lot of noise for no reason. I believe it's much more stable now, and comes pre-installed with newer versions of Rust.

**Comment by sashahilton00** [comment]
Did you update your local branch to use the new dev branch? You might have to delete your local dev branchm, git fetch and switch if you had a branch previously named dev for local development as I did. In any case, the dev and master branches are now even, as I just merged them with my recent changes.

With regards to those recent changes, it's all basically dependencies. I dumped rust-mdns in favour of libmdns, which is on crates.io. rust-tremor has been forked and now resides [here](https://github.com/librespot-org/librespot-tremor), with the old local tremor gone so that librespot can be published to crates.io.

Speaking of crates.io, librespot is now on crates.io, version `0.1.0`. With all the blockages out of the way, I figured we'd waited long enough to get it published, so decided to crack on. I've added some publishing notes which spell out the basics and the order in which things needed to be published, as well as merged my changes with development, development with master, then published from master and tagged it at the time of release. It should hopefully be easier to release now, as the initial PITA was with dealing with crates.io not liking the fact that the project depended on previously unpublished crates.

There is still a discussion to be had on how we wish to version things though, namely do we want per crate versioning, which allows development flexibility from crate to crate, but kills automated publishing when say a new tag is pushed, and also means that the repo version tags will diverge from the crate versions, or do we want repo version tagging, which enables automated releases on tagging, but limits development flexibility from crate to crate, and kind of makes the crates.io packaging redundant? Personally I'm in favour of the latter, but please chime in.

**Comment by ashthespy** [comment]
Woohoo! 🎉 Thanks for the effort! `cargo install librespot` worked just fine on my Windoze..

>Did you update your local branch to use the new dev branch? You might have to delete your local >dev branchm, git fetch and switch if you had a branch previously named dev for local development >as I did. In any case, the dev and master branches are now even, as I just merged them with my >recent changes.

Apparently I looked at it after you merged it, but got confused as I didn't see any merge commits.. 

W.t.r the crate flexibility, given the interdepended nature of the crates, do we really require such flexibility? We should look into `tokio` or one of the other nested crates to get a feel for it..

**Comment by sashahilton00** [comment]
> We should look into `tokio` or one of the other nested crates to get a feel for it..

Had a look into the `rust-protobuf` crate as I noticed the version numbers were the same when updating to exact dependencies, they look to have taken the second approach to versioning, where the repo is versioned. As mentioned previously I'd be fine with this.

**Comment by sashahilton00** [comment]
@dtcooper the recent release on crates.io might also be of interest to you as it ) provides a stable librespot library and b) should make installing librespot easier during the build process.

**Comment by sashahilton00** [comment]
Have just creates a `publish.sh` script and added it to the dev branch, I suggest that we use that for releasing versions in future, as it abstracts away some of the tedious processes. I took an executive decision and decided to work on the basis of repo versioning, so all `librespot-*` crates will have the same version at any given time. The main benefit of this is that we can now setup the CI to run whenever a new tag is pushed to the repo, though we need to do some checking to make sure only semver tags are published. Once that's setup, we shouldn't need to ever manually publish any crates, instead we can just let the CI handle all of that.

If someone has some experience with the Github CI and wants to write up the config for that, it would be most welcome, otherwise I'll do it at some point. Ideally we'd test a release with the script first just to make sure I haven't missed anything.

**Comment by l3d00m** [comment]
Hello, what is the process for merging back dev into master? As far as I've understood is there were quit a lot of improvements commited onto `dev`, which haven't made it into `master` yet.

**Comment by ashthespy** [comment]
> 
> 
> Hello, what is the process for merging back dev into master? As far as I've understood is there were quit a lot of improvements commited onto `dev`, which haven't made it into `master` yet.

Would guess all the changes will be merged into master when a new version is published on crates.io
