### ISSUE TITLE
Strange behaviour in iOS app when using librespot Spotify Connect

### ISSUE THREAD

**Issue by lealoureiro** [librespot-org/librespot#461]
Hello,

First of all thanks for great work!

I notice something a bit strange when using librespot as Spotify Connect device, together with Snapcast.

When I push next song, the now playing window disappears/slides down.
The same doest happen with other devices like my laptop or my Denon Amplifier.

Is not a big deal but is annoying feels like something is different.

Please check the video to see better the problem.

[Screenplay of Issue](https://www.dropbox.com/s/jvk3ucujcaro3yr/RPReplay_Final1586862897.mp4?dl=0)

Regards,
Leandro

**Comment by koloodziej** [comment]
Same problem on Android.

**Comment by ashthespy** [comment]
Just bisected and found that https://github.com/librespot-org/librespot/commit/3f111a97785c1c1d5a77d833a98e5fb085a85399 introduces this..

**Comment by kaymes** [comment]
It seems like Spotify changed the way the app behaves for kPlayStatusLoading. When I wrote this code, I tested it quite a bit with the desktop client (Linux) and the Android app. The behaviour for kPlayStatusLoading was that the desktop client would grey out the progress bar and the Android app just ignored it.
My understanding of kPlayStatusLoading was that it should be sent while loading a track but not yet playing it, so that's what I programmed.

With the new behaviour of the app, it seems like my interpretation of kPlayStatusLoading was wrong because the way the app behaves is indeed annoying and doesn't make sense when loading a track. Maybe it is intended to be sent during the start-up phase of a user-controlled client. I don't know.

In any case, librespot should probably refrain from using kPlayStatusLoading for now.

I created a branch with a simple fix. I'll open a PR in a moment.
