### ISSUE TITLE
Librespot not shown on network and connecting with credentials does not work. Where to start looking?

### ISSUE THREAD

**Issue by Cumol** [librespot-org/librespot#482]
I am using a librespot plugin in Kodi/LibreELEC and cannot get it to work. The person who made the plugin also has no clue what is happening. The thread can be found here: https://forum.libreelec.tv/thread/8438-librespot-addon/?pageNo=35

I was wondering what I can do to trace the root of the problem.

What would cause librespot not to be shown on the network (discovery mode on)?

When discovery mode is off, which credentials should be used (what is "username" in this case)?

Where to look when putting credentials also does not lead to librespot showing in the devices?

**Comment by Malvineous** [comment]
You'll probably have to run librespot directly on its own, because the problem might not even be with librespot.  If you get the same problem running it directly then you'll have eliminated the plugin and other media player as causing the problem, and you'll also be able to post full librespot debugging logs.
