### ISSUE TITLE
disconnect a client and be available for a new one

### ISSUE THREAD

**Issue by jgabriel98** [librespot-org/librespot#499]
This is a feature request, to add the possibility to disconnect a client from librespot, and then keep running, being available for a new connection.

This cenario makes sense when running in zeroconf mode, when you need to disconnect the client from librespot/"server" side. This can be super usefull to implement to MPRIS stop() method, for example.

I'm new to the librespot code, but i think that adding a _Disconnect_ method to **_spirc_** class (in _librespot-connect_ package) would be enough.

If i missed something and there's it is already possible to disconnect a client, please let me know.

**Comment by Malvineous** [comment]
I'm not sure I understand the problem.  Once you disconnect you cannot be available for a new connection as librespot has to initiate the connection to the servers.  Once you have disconnected there is no way to signal a reconnect again, so librespot should exit otherwise it will keep running forever doing nothing.

What is the problem you are having?  You can have multiple connections from multiple devices and just switch between them without needing any of them to disconnect.

**Comment by JasonLG1979** [comment]
> If i missed something and there's it is already possible to disconnect a client, please let me know.

Yes, in the devices menu of the spotify app just select the device itself. It's be called something like "This Phone", "This Tablet", or "This Computer" or whatever.

**Comment by jgabriel98** [comment]
I wanted to do this without needing to touch the spotify app.

But by the time i opnened this issue, i had little knowledge about librespot.
By now i do undertand that this feature request makes no sense.

i will close this.
