### ISSUE TITLE
[Question] Librespot working on ESP32 and/or ESP8266?

### ISSUE THREAD

**Issue by Bart-van-Ingen** [librespot-org/librespot#561]
Hi! A library is available which compiles rust for xtensa processors [https://github.com/MabezDev/rust-xtensa](https://github.com/MabezDev/rust-xtensa). This allows rust to work on ESP32 and/or ESP8266! Do you think that librespot would be able to work on this platform?

**Comment by plietar** [comment]
In theory yes, it probably could.

In practice librespot relies on Rust's `libstd` to provide OS-like functionalities (ie. network, filesystem, threads, ...). In order to get librespot working, you would need a wrapper around the ESP-IDF to expose those APIs, and I'm not aware of anything like that yet.
