### ISSUE TITLE
All messages are sent to stdout, even errors, which should be in stderr.

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#690]
Librespot echoes everything into `stdout`. This could be improved by properly echoing all `INFO` messages to stdout and all `WARN` and `ERROR` messages to stderr.

Currently, when I start librespot with:
```
# ./librespot > /dev/null
```
I would expect all info messages redirected to `/dev/null`, but still see any possible warnings or errors. However, this is not the case.

This also breaks when using `systemd` and specifying:
```
StandardOutput=append:/var/log/librespot.stdout.log
StandardError=append:/var/log/librespot.stderr.log
```

With this configuration, all messages are in the `librespot.stdout.log` file.

**Comment by Johannesd3** [comment]
First of all: AFAIK all log messages are printed to `stderr`, not `stdout`. Which of us is wrong?

I do not agree: `stderr` is in a way a misleading name, because it is thought for all kind of status messages. E.g. curl will print the download progress to `stderr` (if `stdout` is redirected). Or `bash` will show the `$ ` on `stderr`. 

`stdout` is often used for that kind of output that is the purpose of the program, e.g. the list of files in `ls`, the downloaded file in `curl`.

And as a matter of fact, librespot uses already `stdout` for another purpose: If the "pipe" backend is selected, the audio data will be passed to `stdout`. Considering this, your idea doesn't make so much sense anymore.

If you just want to see errors and warning, use the `RUST_LOG` environment variable. If you want to log all messages but see only errors, use `grep` to filter the messages. Another advantage: The order of messages will be preserved if you use a single file.

**Comment by roderickvd** [comment]
I stand corrected, you are right and was mistaken with logging levels. Which should work fine.

@coderootme you should use `2>/dev/null` syntax.

**Comment by coderootme** [comment]
Yes, guys, I am sorry. Everything goes to stderr. My point still stands, however, but it seems like you don't agree with that idea, so I will close it here.
