### ISSUE TITLE
Discovery not disabled when credentials are specified

### ISSUE THREAD

**Issue by aanno** [librespot-org/librespot#742]
(Cross post from https://github.com/Spotifyd/spotifyd/issues/948 as spotifyd uses librespot)

We've got a (paid) spotify family account and I have set up spotifyd with my user. However with this, my son could not 'respot' to spotifyd (but he could see the device in his official spotify android app). Is this the expected behaviour? Is there a way around?

BTW, there a 'dump' devices like speakers that spotify could 'respot' to that are not registered/associated with a spotify account. I wonder if there is way to run spotifyd (i.e. librespot) in a similiar mode?

**Comment by JasonLG1979** [comment]
From what I understand if you provide librespot with credentials you are effectively locking it to that account. I guessing even though he's under the same family account he still has a different username at least? The fact that discovery isn't turned off when credentials are provided is the real bug here.

You shouldn't have to provide credentials at all and it should work in discovery mode. Have you tried that?

**Comment by jonsolberg** [comment]
I'm having a similar issue:

Two premium users for which one cannot connect but can see the Librespot instance (from phone or Windows 10 desktop app). The other user can connect and play just fine, regardless of device.

Discovery is turned on, but user credentials for the working user are present in settings.xml and cache/credentials.json files.

If I remove all settings and turn on discovery both users can see the Librespot instance, but neither of them can connect. No information in the logs for the users that cannot connect in both cases.

So, to me it's a catch 22. Either provide credentials and only allow one user to connect or don't provide them and don't let anyone connect. Discovery mode (which seem to be a new feature as of version 9.2.0.120) does not seem to work with several users or without any credentials provided.

Two users used to work, but some way along the way between 9.2.0.117 to the current 9.2.0.125 it stopped, perhaps due to an update on the Spotify side? Tried them all with clean settings and credentials provided, and older versions without the discovery feature only show for the user with the supplied credentials; I can connect to the instance, but get no sound for versions before x.120.

**Comment by shanemeagher** [comment]
@jonsolberg are you using this from LibreELEC? If so, have you reported on the forum first to confirm it is not a fault with how addon is packaged?

https://forum.libreelec.tv/thread/8438-librespot-addon/

**Comment by roderickvd** [comment]
I just tried connecting to the same `librespot` instance from two different users. It works fine in discovery mode both with and without credentials specified on the command line. 

This is running `librespot` `0.2.0-dev` and I see that `Spotifyd` is still on `0.1.5`.
Please try the latest version and report if this has since been fixed for you.

**Comment by roderickvd** [comment]
Cannot reproduce and no further replies.
