### ISSUE TITLE
Podcasts and low music is distorted

### ISSUE THREAD

**Issue by shumafuk** [librespot-org/librespot#963]
During podcasts (generally speech) and quiet songs I can hear distortions. It is ok with music that is not quiet. I don't want to use any normalisation, dynamic processing, etc. Actually I don't want any processing that modify volume, dynamics etc. It was fine with Raspotify, but not with librespot.

I tried to put --mixer softvol --volume-ctrl fixed --initial-volume 100 in config file, but I don't know where exactly it should be? It does nothing if I put that on new line.

**Comment by JasonLG1979** [comment]
> It was fine with Raspotify, but not with librespot.

What version of Raspotify and what version of `librespot`? Raspotify is literally just the `librespot` binary compiled from the `dev` branch, a config file (really an environment file) and a systemd unit file. If anything Raspotify is the best (certainly the easiest) way to get a really up to date version of `librespot` on Debian based system especially now since I added arm64 and amd64 builds.

You can configure Raspotify (again since it is `librespot`) to be as close to a pass-though as possible in the Raspotify config.

> I tried to put --mixer softvol --volume-ctrl fixed --initial-volume 100 in config file

`librespot` doesn't parse a config file. The "config" file in Raspotify is an environment file. You can't use the commandline args. The Raspotify config file explains how to use it.

**Comment by roderickvd** [comment]
What @JasonLG1979 said.

Only thing I can think of is that you have normalisation enabled (it's disabled by default though), set to dynamic, and you're running into #934. Please try compiling from `dev` and see if the new dynamic limiter fixes that for you.

Or, fix up your configuration and be sure that normalisation is disabled all together which is what you say you want to. Please be advised that we focus on issues here, not on providing configuration support.

**Comment by JasonLG1979** [comment]
@shumafuk if you're having problems understanding how to configure Raspotify, carefully read the [wiki here](https://github.com/librespot-org/librespot/wiki) and [the wiki at the Raspotify repo here](https://github.com/dtcooper/raspotify/wiki) and I'm sure you'll get the answers you need. Otherwise ask your Raspotify specific configuration questions at the Raspotify repo.

@roderickvd I think you can close this. If need be I can pick it up at the Raspotify repo.
